name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  check_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verificar se index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "Erro: public/index.html não encontrado!"
            exit 1
          fi

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-main@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
